name:                Poett
version:             1.0.0
github:              "vmarionneau/Poett"
license:             BSD-3-Clause
author:              "Virgil Marionneau"
maintainer:          "marionneau.virgil@gmail.com"
copyright:           "2025 Virgil Marionneau"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Poett#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- mtl

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  Poett-exe:
    main:                Main.hs
    source-dirs:         bin
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Poett